### ISSUE TITLE
An issue with perl multi-threading

### ISSUE THREAD

**Issue by sagnikbanerjee15** [splicebox/PsiCLASS#16]
Hello,

I have integrated `psiclass` into a gene annotator pipeline called `finder`. You can check out the preprint https://www.biorxiv.org/content/10.1101/2021.02.04.429837v1.full

One of the users has reported an issue with Perl multi-threading. The precise error returned by `psiclass` is

```
This Perl not built to support threads
Compilation failed in require at /home/i7_station/bin/finder/dep/psiclass_terminal_exon_length_modified/psiclass line 9.
BEGIN failed--compilation aborted at /home/i7_station/bin/finder/dep/psiclass_terminal_exon_length_modified/psiclass line 9.
```

The line from the `psiclass` file is `Use threads;`

The user is running `finder` within a conda environment that has `perl-thread` installed. But still it returns this error. Could you please look into it?

Thanks.

**Comment by mourisl** [comment]
Thanks for the information. I just checked perl's documentation, it seems this "threads" was introduced in Perl 5.8. Could the user install the newer version of perl in Conda? My system uses perl 5.16.

**Comment by sagnikbanerjee15** [comment]
I have requested the user to post the version of perl. I have provided an environment.yml file from which the conda environment was constructed (https://github.com/sagnikbanerjee15/Finder/blob/master/environment.yml). In this file perl version is set to 5.26.

**Comment by sagnikbanerjee15** [comment]
Hi,

The user was able to fix it after a fresh reinstallation.

Thanks

**Comment by mourisl** [comment]
Thank you for letting us know!
