### ISSUE TITLE
Unknown genome name: -1 error

### ISSUE THREAD

**Issue by NicolaVitulo** [splicebox/PsiCLASS#18]
Hi,
I'm using PsiClass on 12 different RNA-seq samples. The data were aligned using gsnap aligner.
When I run PsiClass, it creates all the psiclass_bam_*.raw_splice expected files. 
However, when it runs the **trust-splice** program, the program exits after creating a  **psiclass_bam.trusted_splice** file containing the following: **Unknown genome name: -1**

This is an example of the first lines of one of the *.raw_splice file:

chr1c 22726 23208 2 - 2 0 0 0
chr1c 23345 40563 2 - 2 0 0 0
chr1c 23509 40563 9 - 9 0 1 0
chr1c 48405 48513 140 - 140 0 28 0

The program exits simply printing  "Terminated" 

I already used this program using the same options  on another similar project but I did not have any problems.

Thank you very much for any help!

**Comment by mourisl** [comment]
I guess GSNAP might still print CIGAR string with intron information for those unmapped reads somehow(?). I just fix this issue by skipping the alignments with no chromosome information. Could git pull the new version and give it a try? Thank you.

**Comment by NicolaVitulo** [comment]
Thank you very much for your quick replay!
It works! 
It is weird , I used to remove the unmapped reads ... moreover in another project I did not have any problem using gsnap as aligner..
Thank you again!

**Comment by mourisl** [comment]
Another possible reason is that the header is incomplete and misses some chromosomes (such as alternative contigs). Do the final assemblies look normal?

**Comment by NicolaVitulo** [comment]
I think I found the problem.
There was a problem with the header of the bam file. For some reason, the first line of the alignment started with a "@" symbol, as in the header. I upgrade gsnap version to the last  one available, this solved the problem.
Thank you again for your help.
