### ISSUE TITLE
Maximum number of samples 

### ISSUE THREAD

**Issue by sagnikbanerjee15** [splicebox/PsiCLASS#2]
Hello,

I foresee a time in the near future when I will be working with a very large number of samples (~2K) from various different sources of the same organism. Will PsiCLASS be able to handle such a large number of samples assuming there is sufficient memory and hard disk space?

Thank you.

**Comment by mourisl** [comment]
The largest one I tried have 667 samples. 2K samples should be fine, but may take 50G memory.

**Comment by sagnikbanerjee15** [comment]
Awesome! Thanks.
