### ISSUE TITLE
Encountering segmentation fault

### ISSUE THREAD

**Issue by sagnikbanerjee15** [splicebox/PsiCLASS#21]
Hello,

I am experiencing a segmentation fault while trying to assemble a transcriptome. Here is the log file.

```
0: 1 I 1668 1873. Free threads: 39/40
1: 3 I 2478 3268. Free threads: 38/40
2: 1 I 3355 3905. Free threads: 37/40
3: 32 I 4115 16850. Free threads: 36/40
1668: atCnt=1 seCnt=1 0 0 0
2478: atCnt=2 seCnt=3 0 0 0
Thread 38: I 1668 1873 finished.
Thread 37: I 2478 3268 finished.
3355: atCnt=1 seCnt=1 0 0 0
Thread 36: I 3355 3905 finished.
4: 1 I 17197 17449. Free threads: 38/40
5: 22 I 17452 26866. Free threads: 37/40
17197: atCnt=1 seCnt=1 0 0 0
Thread 37: I 17197 17449 finished.
4115: atCnt=109 seCnt=32 1 44 133
17452: atCnt=27 seCnt=22 0 39 103
Thread 37: I 17452 26866 finished.
6: 24022 I 27601 15071360. Free threads: 38/40
Thread 36: I 4115 16850 finished.
7: 1 I 15071979 15072427. Free threads: 38/40
8: 31 IV 641 15640. Free threads: 37/40
15071979: atCnt=1 seCnt=1 0 1 1
Thread 37: I 15071979 15072427 finished.
27601: atCnt=18023655 seCnt=24022 1 25774 75439
```

This is the command that produced the fault:

```
/lustre/project/maizegdb/sagnik/FINDER/Finder/dep/psiclass_terminal_exon_length_modified/classes -p 40 --primaryParalog --lb /lustre/project/maizegdb/sagnik/FINDER_troubleshoot/bshrestha/finder_results/assemblies_psiclass_modified/fofn -s /lustre/project/maizegdb/sagnik/FINDER_troubleshoot/bshrestha/finder_results/assemblies_psiclass_modified/combined/subexon/psiclass_output_subexon_combined.out -o /lustre/project/maizegdb/sagnik/FINDER_troubleshoot/bshrestha/finder_results/assemblies_psiclass_modified/combined/psiclass_output > /lustre/project/maizegdb/sagnik/FINDER_troubleshoot/bshrestha/finder_results/assemblies_psiclass_modified/combined/psiclass_output_classes.log
```

Could you please look at this?

Thank you.

**Comment by mourisl** [comment]
It looks like a gene (or several overlapped) spanning "I:27601-15071360" is very long, could the memory allocation from the server is not enough for this region?

**Comment by sagnikbanerjee15** [comment]
I checked and found that the total memory consumed was ~ 8 GB which is much less that the max limit.

Thanks.

**Comment by mourisl** [comment]
Could you please share the psiclass_output_subexon_combined.out and maybe one sample's subset of bam file with reads from chromosome I with me? I can take a look.

**Comment by sagnikbanerjee15** [comment]
Here you are.

The bam file is too large to be put in this chat. Can I email it somewhere?
[psiclass_output_subexon_combined.out.zip](https://github.com/splicebox/PsiCLASS/files/7461520/psiclass_output_subexon_combined.out.zip)


Thank you.

**Comment by mourisl** [comment]
Thanks for sharing. I don't need the full bam file. Could you please use "samtools view -b XX.bam I > subset.bam" to get the subset? If it is still large, maybe can you share it through google drive or dropbox? Thanks.

Or just even the header of bam file would be quite helpful, so I can create a dummy bam file to run.

**Comment by sagnikbanerjee15** [comment]
Hi,

Here is the header of the bam file.

[header.zip](https://github.com/splicebox/PsiCLASS/files/7461965/header.zip)

Please let me know if you need anything else from my side.

Thanks.

**Comment by ZuyaoLiu** [comment]
@sagnikbanerjee15 @mourisl 
I have the same problem when using PsiCLASS in Finder.

**Comment by mourisl** [comment]
Thanks for providing the files. I think I've found and fixed bug based on the data. Could you please pull the new version and give it a try? Thank you.

**Comment by ZuyaoLiu** [comment]
@mourisl 
Thanks. The issue has been solved and everything works well now from my side.

**Comment by sagnikbanerjee15** [comment]
Thank you @mourisl. It works now.
