### ISSUE TITLE
Core dumped when combine-subexons

### ISSUE THREAD

**Issue by xiekunwhy** [splicebox/PsiCLASS#23]
Hi,

Why core dumped in combine-subexons step?

Here is the error log,
sh: line 1: 60345 Segmentation fault      (core dumped) combine-subexons --ls 02.psiclass_subexon.list > 02.psiclass_subexon_combined.out
Terminated

Here are the files in 02.psiclass_subexon.list (you need to unzip first)

[02.psiclass_subexon_0.zip](https://github.com/splicebox/PsiCLASS/files/7888132/02.psiclass_subexon_0.zip)
[02.psiclass_subexon_1.zip](https://github.com/splicebox/PsiCLASS/files/7888137/02.psiclass_subexon_1.zip)
[02.psiclass_subexon_2.zip](https://github.com/splicebox/PsiCLASS/files/7888143/02.psiclass_subexon_2.zip)

Best,
Kun

**Comment by mourisl** [comment]
Thanks for providing the files. I will look into this issue.

**Comment by mourisl** [comment]
Which PsiCLASS version did you use? There are some bugs fixed in the combine-subexons after the release of 1.0.2, so the "git clone" version might work.

If this is not the case, could you please create a dummy bam file with command like "samtools view -bH /state/partition1/WORK/Bio/Project/xiek/project/GDDEPRB21010357/GDDEPRB21010357_std_19/develop/02.mRNA/01.mapping/Opm-te1.sort.bam > dummy.bam" and share the dummy file with me? I need the chromosome/scaffolding information in the bam file to debug. Thank you!

**Comment by xiekunwhy** [comment]
Hi,

I use version 1.0.2.
psiclass --version
PsiCLASS v1.0.2
So this is not the case.

Here is the dummy bam
[dummy.zip](https://github.com/splicebox/PsiCLASS/files/7891074/dummy.zip)

Best,
Kun

**Comment by mourisl** [comment]
Thanks again for providing the bam file. I just tested the data on the current version of PsiCLASS, and it finishes without any error or abnormal memory access pattern. Could you please use "git clone" to get the github version of PsiCLASS and give it a try? Even though the version number says 1.0.2, there are some fixes. If the github version works, I will create a new release. Thank you!

**Comment by xiekunwhy** [comment]
Hi,

Not work even use "git clone" to get the github version. I think you need to create a new release, the conda version also not worked (missing samtools).

Best,
Kun

**Comment by xiekunwhy** [comment]
Hi,

This problem appear again, I use psiclass in five species, 3 were run through and 2 were core dumped. Would please create a new release.

Best,
Kun

**Comment by xiekunwhy** [comment]
It worked through when I replace combine-subexons in github version(after make) by conda version, but combine-subexons in conda version has no -q option.

**Comment by mourisl** [comment]
Ah. I see. I thought you already tried the combine-subexons from github and was still trying to debug the issue. Since the github version resolves your issue, I will draft a new release and the conda will be automatically updated later. Thank you!

**Comment by xiekunwhy** [comment]
No No No, the conda version combine-subexons resolves my issue, not github version.

**Comment by mourisl** [comment]
On the test data you shared, there was no error on our server, even with memory profiling tools. I will try it on another computer to see whether I can reproduce this error.

**Comment by xiekunwhy** [comment]
Or, can you send me your local version source code, I have tried github version many times.

**Comment by mourisl** [comment]
I just updated the Makefile in the github to allow some error debug output information. Can you still use the github code of CombineSubexons.cpp, run a "make clean" first, and then run "asan=1 make" to activate the debug mode. Then the error message should be output on the screen, and you can share that with me and I will look into this issue. Thank you!

**Comment by xiekunwhy** [comment]
Hi,

Here is the error log, my gcc/g++ version is 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC), too low?

asan=1 make
g++ -c -o subexon-info.o -I./samtools-0.1.19 -L./samtools-0.1.19 -Wall -O3  -fsanitize=address -g SubexonInfo.cpp -lbam -lz -lm -lpthread  -fsanitize=address -ldl -g
cc1plus: error: unrecognized command line option "-fsanitize=address"
cc1plus: error: unrecognized command line option "-fsanitize=address"
make: *** [subexon-info.o] Error 1

**Comment by mourisl** [comment]
Yes, seems the gcc version is too low. I tested gcc v5.5 on our system, and it works. Do you have a relative newer version on your system? Thank you.

**Comment by xiekunwhy** [comment]
Things worked well when we use gcc-9.1.0, thank you very much. And you can close this issue.

**Comment by mourisl** [comment]
Thank you for your patient tests! I will try to find a machine with GCC v4 and test your data again in near future! I will close the issue for now.
