### ISSUE TITLE
Getting frequent Segmentation fault errors

### ISSUE THREAD

**Issue by sanyalab** [splicebox/PsiCLASS#24]
Hello,

I am trying to run the following command and getting "Segmentation Fault" errors. Below is the error

`sh: line 1: 26387 Segmentation fault      (core dumped) /scale03/fs0/gpfs0/research/anno/sanyalab/SOFTWARE/psiclass/combine-subexons --ls ./subexon/Hap1_psiclass_subexon.list > ./subexon/Hap1_psiclass_subexon_combined.out`
`Terminated`

My Command was
`nohup /anno/sanyalab/SOFTWARE/psiclass/psiclass -b STAR-HAP1/egg_lateAligned.sortedByCoord.out.bam,STAR-HAP1/Instar_1_Aligned.sortedByCoord.out.bam,STAR-HAP1/Instar_2_Aligned.sortedByCoord.out.bam,STAR-HAP1/Instar_3_Aligned.sortedByCoord.out.bam,STAR-HAP1/Instar_3_gut_Aligned.sortedByCoord.out.bam,STAR-HAP1/pupa_Aligned.sortedByCoord.out.bam,STAR-HAP1/unmated_adult_female_Aligned.sortedByCoord.out.bam,STAR-HAP1/unmated_adult_male_Aligned.sortedByCoord.out.bam -p 14 --vd 1.5 --stage 0 -o Hap1_psiclass`

Each BAM file is between 9GB - 13GB. I have a RAM of 256GB. I have done alignment using STAR. This command worked fine with HISAT2. HISAT2 alignment files were also between 9GB - 13GB.

I can use the cluster and specify a higher memory. However, I do not know whether I should be giving the complete path to the prefix in "-o" like so "-o /Full/Path/2/Out_prefix"

Please advice what I should be doing. I am on an ubuntu x86_64 machine.

Thanks
Abhijit

**Comment by mourisl** [comment]
Which version of PsiCLASS are you using? Could you please share the subexon files in the subexon folder for me to debug with? Thanks.

**Comment by sanyalab** [comment]
Hello,

I am using the latest psiclass v1.0.2. The subexon folder is 218 MB. Let me
know if you are able to get the same.

Thanks
Abhijit
 subexon.zip
<https://drive.google.com/file/d/1pC5KR-DxfpN-RmgZDqx9JtAOQEvxSoo4/view?usp=drive_web>

**Comment by mourisl** [comment]
It seems the current github version does not crash on our server. Could you please use git pull or git clone to use the most updated version? If it resolves your issues, I will draft a new release. Thank you.

**Comment by sanyalab** [comment]
Ok! Doing this now. Will post on the results. Thank you so much.

-Abhijit

**Comment by sanyalab** [comment]
Getting Segmentation fault again. Seems to be working fine with HISAT2 created BAM files.

-Abhijit

**Comment by mourisl** [comment]
Could you please recompile PsiCLASS with the debug mode : "make clean" and then "asan=1 make"? This time if the program crashes, it should print which part causes the issue. To save time, you can run psiclass with the option "--stage 2" to directly start from the combine subexon step. Thank you.

**Comment by sanyalab** [comment]
Hi,
Here is what is happening.

`lxjh218:.../SOFTWARE/psiclass$ make clean`
`rm -f *.o *.gch subexon-info combine-subexons trust-splice vote-transcripts junc grader add-genename addXS`

`lxjh218:.../SOFTWARE/psiclass$ asan=1 make`
`g++ -c -o subexon-info.o -I./samtools-0.1.19 -L./samtools-0.1.19 -Wall -O3  -fsanitize=address -g SubexonInfo.cpp -lbam -lz -lm -lpthread  -fsanitize=address -ldl -g`
`cc1plus: error: unrecognized command line option "-fsanitize=address"`
`cc1plus: error: unrecognized command line option "-fsanitize=address"`
`make: *** [subexon-info.o] Error 1`

So then I did just `make`. Attached is the STDOUT.
[make_for_psiclass.txt](https://github.com/splicebox/PsiCLASS/files/8527062/make_for_psiclass.txt)

Thanks
Abhijit

**Comment by mourisl** [comment]
What is the gcc version on your system? You may need to use a newer version.

**Comment by sanyalab** [comment]
`lxjh218:.../SOFTWARE/psiclass$ gcc --version`
`gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)`

**Comment by sanyalab** [comment]
I installed psiclass using conda. This time the error is different. Below

`sh: /Anaconda3/envs/SRAssembly1/bin/samtools-0.1.19/samtools: No such file or directory`
`Found mate read id index suffix(.1 or /1). Calling "--mateIdx 1" option. If this is a false calling, please use "--mateIdx 0".`
`/Anaconda3/envs/SRAssembly1/bin/junc /STAR-RESULT/Sample1_Aligned.sortedByCoord.out.bam -a  --hasMateIdSuffix > ./splice/Hap1_psiclass_bam_0.raw_splice`
`/Anaconda3/envs/SRAssembly1/bin/junc /STAR-RESULT/Sample2_Aligned.sortedByCoord.out.bam -a  --hasMateIdSuffix > ./splice/Hap1_psiclass_bam_1.raw_splice`
`/Anaconda3/envs/SRAssembly1/bin/junc /STAR-RESULT/Sample3_Aligned.sortedByCoord.out.bam -a  --hasMateIdSuffix > ./splice/Hap1_psiclass_bam_2.raw_splice`
`/Anaconda3/envs/SRAssembly1/bin/junc /STAR-RESULT/Sample4_Aligned.sortedByCoord.out.bam -a  --hasMateIdSuffix > ./splice/Hap1_psiclass_bam_3.raw_splice`
`/Anaconda3/envs/SRAssembly1/bin/junc /STAR-RESULT/Sample4_V1_Aligned.sortedByCoord.out.bam -a  --hasMateIdSuffix > ./splice/Hap1_psiclass_bam_4.raw_splice`
`/Anaconda3/envs/SRAssembly1/bin/junc /STAR-RESULT/Sample5_Aligned.sortedByCoord.out.bam -a  --hasMateIdSuffix > ./splice/Hap1_psiclass_bam_5.raw_splice`
`/Anaconda3/envs/SRAssembly1/bin/junc /STAR-RESULT/Sample6_Aligned.sortedByCoord.out.bam -a  --hasMateIdSuffix > ./splice/Hap1_psiclass_bam_6.raw_splice`
`/Anaconda3/envs/SRAssembly1/bin/junc /STAR-RESULT/Sample7_Aligned.sortedByCoord.out.bam -a  --hasMateIdSuffix > ./splice/Hap1_psiclass_bam_7.raw_splice`
`/Anaconda3/envs/SRAssembly1/bin/trust-splice ./splice/Hap1_psiclass_splice.list /STAR-RESULT/Sample1_Aligned.sortedByCoord.out.bam  > ./splice/Hap1_psiclass_bam.trusted_splice`
`perl /Anaconda3/envs/SRAssembly1/bin/FilterSplice.pl ./splice/Hap1_psiclass_bam_0.raw_splice ./splice/Hap1_psiclass_bam.trusted_splice > ./splice/Hap1_psiclass_bam_0.splice`
`Can't open perl script "/Anaconda3/envs/SRAssembly1/bin/FilterSplice.pl": No such file or directory`
`Terminated`

I think I need samtools v0.1.19 to be installed in conda.

**Comment by sanyalab** [comment]
I installed samtools v0.1.19 in conda. It still is looking for samtools at the following address

`/mnt/common/rh6/annotate/Anaconda3/envs/SRAssembly1/bin/samtools-0.1.19/samtools` but samtools is present at `/mnt/common/rh6/annotate/Anaconda3/envs/SRAssembly1/bin` and it is the first entry in PATH.

Samtools needs to be packaged correctly in conda I think.

-Abhijit

**Comment by mourisl** [comment]
Can you use the command like "export PYTHONUSERBASE=intentionally-disabled" to force the system in conda?
