### ISSUE TITLE
Mixture of paired-ended and single-ended read aligments

### ISSUE THREAD

**Issue by sagnikbanerjee15** [splicebox/PsiCLASS#5]
Hello,

I was wondering if PsiCLASS can handle single-ended read alignments and paired-ended read alignments in the same alignment file. How does it deal with reads whose pairs are unaligned? 

Also, can PsiCLASS annotate micro-exons (size less than 10 nucl) if the alignment to that exon exists?

Thank you.

**Comment by mourisl** [comment]
If they are in the same bam file, PsiCLASS could not handle that. Since single-end reads and pair-end reads should be from two samples, it would be better to give 2 bams for PsiCLASS.
For the paired-end reads whose mate is not aligned, PsiCLASS still uses the information to identify exons, genes and rough transcripts. But in final decision and abundance estimation, it only uses alignments whose both mates are aligned.

For the exon size, as long as the aligner can identify those, PsiCLASS has no restriction on that.

**Comment by sagnikbanerjee15** [comment]
Thank you for your reply.

In your experience, do you think one might lose significant sensitivity if the paired-ends are converted to single-end? 

Thank you.

**Comment by mourisl** [comment]
Not much. That's why in PsiCLASS's method, we first regard the data set as single-end to get the candidate transcripts fast, and then use pair-end information to refine the candidates.

**Comment by sagnikbanerjee15** [comment]
Great thanks!!

**Comment by Xiaofei-git** [comment]
Dear @mourisl,

Here is the code I used for mixture of SR and PE:

./psiclass -b merged_24Smps_picard_SR.bam,merged_24Smps_picard_PE.bam -p 16 -o ../assembly/psicalss_24Smps

How long is expected to get the results? I expect to get the output very fast, but it looks like it runs forever and no output in the files. Do you know what happening to my run, or something wrong?

Thanks a lot!

Xiaofei

<img width="578" alt="Screen Shot 2020-06-15 at 11 44 42 AM" src="https://user-images.githubusercontent.com/22894969/84678290-d616d180-aefd-11ea-93d9-36770e522b4d.png">

**Comment by mourisl** [comment]
I think you merged all the 24 samples in the same bam files by Picard. In PsiCLASS, we would recommend providing the bam files separately. Since each sample will introduce some noise, such as wrong introns, these noises could be filtered based on the signal from other samples. PsiCLASS keeps as detail as possible for the gene structure, so if there are too many noises, the gene structure would be too complicated to be resolved efficiently.

**Comment by Xiaofei-git** [comment]
Yes, I merged 22samples from SR for merged_24Smps_picard_SR.bam, and 2 samples from PE for merged_24Smps_picard_PE.bam. So, you mean I need feed PsiCLASS the single bam files?

**Comment by mourisl** [comment]
Yes. You can also use --lb to specify a file, where each line corresponds to a bam file.

**Comment by Xiaofei-git** [comment]
> Yes. You can also use --lb to specify a file, where each line corresponds to a bam file.

Thanks!

**Comment by Xiaofei-git** [comment]
I feed it use single bams, but still don't get voted gff. I did get it so fast for other datasets. 
I see there is no update to the log file since last night 19:27. Do you know how can I know which step it is running? Thanks a lot!

<img width="508" alt="Screen Shot 2020-06-16 at 4 52 02 PM" src="https://user-images.githubusercontent.com/22894969/84827116-fa53da80-aff1-11ea-9911-ccc4ab83abe2.png">

**Comment by mourisl** [comment]
Could you please share the classes.log file with me? Based on the feedback from you and Sagnik, I'm planning to work on some more drastic heuristic filters for the over-complicated gene structures. Thanks.

**Comment by Xiaofei-git** [comment]
> heuristic

I sent it by gmail, let me know if you did't receive it.

**Comment by mourisl** [comment]
@Xiaofei-git Sorry for the late reply. Which email address did you send to, I haven't received any email yet? In the meantime, I updated the program a little bit so it should be much faster handling complicated regions. Could you please give it a try? Thanks.

**Comment by Xiaofei-git** [comment]
Sorry, it was failed to deliver because of the big size. How can I send it
to you?

To try the updated version, I need to re-install it, right?

Thanks!

Xiaofei

**Comment by mourisl** [comment]
Maybe google drive or dropbox? 

Yes, you need to recompile the code. Then you can run psiclass with option --stage 3 since the files from the first stages should be the same.

**Comment by Xiaofei-git** [comment]
https://drive.google.com/file/d/1IDjlmjJ-PR8jN4IM9Cu9FLKXDshm24-P/view?usp=sharing

Can you open it? Thanks!

Xiaofei

**Comment by mourisl** [comment]
Thanks! I've downloaded the file and will look into the issue.

**Comment by Xiaofei-git** [comment]
> Maybe google drive or dropbox?
> 
> Yes, you need to recompile the code. Then you can run psiclass with option --stage 3 since the files from the first stages should be the same.

Not sure if I recompile it successfully, because I got this in the log file:

$ more psicalss_24Smps_new_classes.log
Must use -s option to speicfy subexon file.

Does that mean I have to provide the trusted splice file from the run without voted gff?

**Comment by mourisl** [comment]
You need to have the XXX_subexon_combined.out file in the "subexon" folder. Sorry for the confusion, the "--stage 3" option would assume you have the files generated from previous stages there in folders.

**Comment by Xiaofei-git** [comment]
> You need to have the XXX_subexon_combined.out file in the "subexon" folder. Sorry for the confusion, the "--stage 3" option would assume you have the files generated from previous stages there in folders.


I provided the "-s" option, but still get the error of "Must use -s option to speicfy subexon file." Any mistake I made.


pathTO/psiclass --lb pathTO/cab_bam_24smp.txt -p 16 -s pathTO/psicalss_24Smps_sep_subexon_combined.out --stage 3

**Comment by mourisl** [comment]
Oh, I see. The error message is intended for one of the internal programs in the wrapper psiclass. It is actually not the "-s" in psiclass. I've updated the error message so it will be less confusing.

You can just directly rerun psiclass with the same other options under the folder where you ran psiclass the first time. It should be able to find the subexon_combined.out automatically.

**Comment by Xiaofei-git** [comment]
But still need recompile the code, right?

**Comment by mourisl** [comment]
Yes, you need to recompile the code.

**Comment by Xiaofei-git** [comment]
Thanks!

**Comment by Xiaofei-git** [comment]
> Oh, I see. The error message is intended for one of the internal programs in the wrapper psiclass. It is actually not the "-s" in psiclass. I've updated the error message so it will be less confusing.
> 
> You can just directly rerun psiclass with the same other options under the folder where you ran psiclass the first time. It should be able to find the subexon_combined.out automatically.

I have already submitted the job, but still don't get the results yet and don't see any more processes than the previous run. Do you have ideas based on the sent log file? Any comments on genome size and heterozygosity VS the complicated regions? There are both primary contigs and haplotigs (the alternative haplotype seq. where the assembler could phase two haplotypes) in the assembly.

**Comment by mourisl** [comment]
From your log file, there were two regions PsiCLASS got stuck on. Unfortunately, the log file does not report the contig id (I'm adding that). The two regions start at coordinate 68701 and 734027. You shall find the contig id by searching these two numbers in subexon/XX_subexon_combined.out file. From the log, it seems these two regions are not that complicated and should be finished relatively fast. Is it possible for you to share the alignment from one of your samples on the contig containing the 734027 region, and also the rows of combined_subexon containing that contig? Thank you.

**Comment by Xiaofei-git** [comment]
> From your log file, there were two regions PsiCLASS got stuck on. Unfortunately, the log file does not report the contig id (I'm adding that). The two regions start at coordinate 68701 and 734027. You shall find the contig id by searching these two numbers in subexon/XX_subexon_combined.out file. From the log, it seems these two regions are not that complicated and should be finished relatively fast. Is it possible for you to share the alignment from one of your samples on the contig containing the 734027 region, and also the rows of combined_subexon containing that contig? Thank you.

Here are the rows of combined_subexon containing contigs related to 68701 and 734027:

VvCabSauv08_v1_Primary000599F 68701 68734 0 0 . . -1 -1 -1 0.000000 0.000000 0 0 
VvCabSauv08_v1_Primary000377F 68701 69073 0 2 . - -1 -1 -1 -1.000000 0.983495 0 2 69074 69164 
VvCabSauv08_v1_Haplotig000054F_003 68551 68701 0 0 . . -1 -1 -1 0.000000 0.000000 0 0 

VvCabSauv08_v1_Primary000081F 734027 734046 0 2 . + -1 -1 -1 -1.000000 1.000000 0 2 734047 1303109 


Here is the one of the alignment file of smallest size containing Contig of "VvCabSauv08_v1_Primary000081F" related to 734027 region:
https://drive.google.com/file/d/11DrFcN4cmqtSjeXWya8i3v7fPcQ_MAJd/view?usp=sharing

Thank you so much!

**Comment by mourisl** [comment]
Thanks for sharing the bam file. Can you share the subexon file by grep the rows from contig "VvCabSauv08_v1_Primary000001F"? Sorry for the trouble.

**Comment by Xiaofei-git** [comment]
There are more 10,000 line for that, so I uploaded, so that you can download it.

https://drive.google.com/file/d/1RrreYpdX3qkTLO9-5INxAb8RHcwX9L8f/view?usp=sharing

Thank you so much for your time walking through this with me!

**Comment by mourisl** [comment]
Which gcc version did you use to compile PsiCLASS? I found there might be a thread-safe issue. In the meantime, maybe you can try to run psiclass with single-thread but still with option "--stage 3".

**Comment by Xiaofei-git** [comment]
> Which gcc version did you use to compile PsiCLASS? I found there might be a thread-safe issue. In the meantime, maybe you can try to run psiclass with single thread (-p 1) but still with option "--stage 3".

It is gcc version 7.3.0 (GCC). 

In fact, I met an error when I compiled PsiCLASS. It complained  it can’t find the zlib (libz.so). So, 3 Makefiles were hacked (psiclass, psiclass/samtools-0.1.19, and psiclass/samtools-0.1.19/misc), adding “-L PATHto/software/Compiler/GCCcore/7.3.0/zlib/1.2.11/lib”, and got it built.

Do you remember we have a thread here (https://github.com/mourisl/CLASS/issues/1) talking about it at the bottom?

**Comment by Xiaofei-git** [comment]
> Which gcc version did you use to compile PsiCLASS? I found there might be a thread-safe issue. In the meantime, maybe you can try to run psiclass with single thread (-p 1) but still with option "--stage 3".

I tried to run with "-p 1", but still got stuck. 

At the meantime, I tried to run PsiCLASS on each of single bam file. All 24 runs of single psiclass worked fine, and got the voted gtf. 

Do you think it might be due to the mixture of PE and SR data?

**Comment by mourisl** [comment]
The mixture of PE and SR should be fine. What's puzzling me is that the regions from your combine_subexon.out file are not that complicated. I tried to play around the bam files you shared with several ways to make the alignments more complicated, all of the trials could be finished within seconds. The sever I used to develop PsiCLASS has been down for a few days, I'll try some other methods later. Thanks.

**Comment by Xiaofei-git** [comment]
Thank you so much!

I also played with several runs with my data by combing different bams,
when I got the results, I will update here. Thanks a lot!

**Comment by mourisl** [comment]
@Xiaofei-git After analyzing the subexon file you shared, I found that the intron length is relatively shorter than human data. So some of the filters for the long intron might not be effective in your case. I updated the code to automatically decide the long intron size. Can you pull the new version and give it a try? For this one, you need to rerun PsiCLASS from stage 0. Thanks.

**Comment by Xiaofei-git** [comment]
Sure, thanks a lot!

**Comment by Xiaofei-git** [comment]
> @Xiaofei-git After analyzing the subexon file you shared, I found that the intron length is relatively shorter than human data. So some of the filters for the long intron might not be effective in your case. I updated the code to automatically decide the long intron size. Can you pull the new version and give it a try? For this one, you need to rerun PsiCLASS from stage 0. Thanks.

I submitted the job with the new updated tool. But it looks like still stuck somewhere. The new jobs were started to run on July 16.

**Comment by Xiaofei-git** [comment]
Here is the list of test runs on different combinations of samples:

There are 24 samples in total, 22 of them are SR, and 2 are PE (2aRt and 2bRt).

I was thinking if the alignment file for 2aRt was corrupted, so I rerun the alignment step, but it turned that it is not helpful. 
<img width="246" alt="Screen Shot 2020-07-20 at 5 06 24 PM" src="https://user-images.githubusercontent.com/22894969/87986739-86eb3000-caab-11ea-832b-de6ab7487d5f.png">

**Comment by mourisl** [comment]
It feels that 2aRt is indeed creating a problem here. Could you please share the alignment from 2aRt in region VvCabSauv08_v1_Primary000081F:734027-1353207? 
You can do this with command
"samtools view -b 2aRt VvCabSauv08_v1_Primary000081F:734027-1353207 > tmp.bam" . You need to create the bam index file first with "samtools index" though. 

Sorry for the trouble, but this really helps me a lot.

**Comment by Xiaofei-git** [comment]
> It feels that 2aRt is indeed creating a problem here. Could you please share the alignment from 2aRt in region VvCabSauv08_v1_Primary000081F:734027-1353207?
> You can do this with command
> "samtools view -b 2aRt VvCabSauv08_v1_Primary000081F:734027-1353207 > tmp.bam" . You need to create the bam index file first with "samtools index" though.
> 
> Sorry for the trouble, but this really helps me a lot.

You are so welcome. I really appreciate your time to walk through this with me. Thanks a lot!

Here is the link for the bam in that region:

https://drive.google.com/file/d/1oQNxHlH0BWsv3HI4gI3yIApBXUEP-mEX/view?usp=sharing

**Comment by mourisl** [comment]
@Xiaofei-git Sorry for the late reply, I had many coding projects going on recently. On our server, I can finish the data you shared in 10 minutes, which is of course still slow.

The existing heuristics could not handle the data you shared efficiently, therefore I implemented a new way to speed up PsiCLASS. In this implementation, PsiCLASS finished your data in about 1 minute. On other data, the new approach seems not affects the overall performance and is only triggered for some complicated case. If you are still available for this, could you please give the new code a try? If you find PsiCLASS still get stuck, you can try lower numbers for the option "--maxDpConstraintSize" (default is 7).

Thanks.
