### ISSUE TITLE
How important is the addXS step?

### ISSUE THREAD

**Issue by sagnikbanerjee15** [splicebox/PsiCLASS#7]
Hello,

I was just wondering how important is the addXS step? This step is taking a very long time to finish so I was thinking about eliminating it. Please let me know how it would impact PsiCLASS.

Thank you.

**Comment by mourisl** [comment]
If there is no XS field in the bam, PsiCLASS won't be able to decide the strand of the read/intron, which is critical for the assembly. Most of the RNA-seq aligner will report the XS field by default. For STAR, there is an option "--outSAMstrandField" for this.

**Comment by sagnikbanerjee15** [comment]
So if I configure STAR to output the XS field can I skip the addXS step?

**Comment by mourisl** [comment]
Yes, you can.

**Comment by sagnikbanerjee15** [comment]
Great thanks!
